route:
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 2m
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: "7952190192:AAExWThaJKMx94GSiIlDazJAogrXCGy3rXo"
        chat_id: 1424262912
        parse_mode: 'HTML'
        message: |
          <b>{{ .Status | toUpper }}</b>
          {{ range .Alerts }}
          <b>{{ .Annotations.summary }}</b>
          {{ .Annotations.description }}
          Labels: {{ .Labels }}
          StartsAt: {{ .StartsAt }}
          {{ end }}
